### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by MrHallway0** [danigm/gnome-tour#1]
I am confused on how to build it. When running `meson build && meson compile -C build` on Ubuntu 20.04 I get `meson.build:13:0: ERROR: Dependency "gdk-pixbuf-2.0" not found, tried pkgconfig and cmake`. If you could help me that would be amazing... I'm probably just doing something dumb...

**Comment by danigm** [comment]
You've a missing dependency. Use flatpak to build this, so you have all the dependencies:

```
$ flatpak-builder --repo=repo build/ build-aux/org.gnome.TourDevel.json
```

The easiest way to build the devel version of this is to just use [GNOME Builder](https://wiki.gnome.org/Apps/Builder), with that you should only click the play button on builder and it'll build and run the flatpak package for you.

**Comment by MrHallway0** [comment]
I am using GNOME Builder but is there an `apt` command I need to run.
Sorry I'm new to this stuff!

**Comment by danigm** [comment]
it should work by default on Builder if you have flatpak installed on your system. Maybe it's because this project is outdated. This is a fork to test with custom images, but the original project is here: https://gitlab.gnome.org/GNOME/gnome-tour

Maybe you can test with the latest version to see if it works for you.

**Comment by MrHallway0** [comment]
Thank you for your help!
